### ISSUE TITLE
Comparison to built-in gn and gN

### ISSUE THREAD

**Issue by Asheq** [kana/vim-textobj-lastpat#5]
Hey kana,

How does this text object compare to the built-in `gn` and `gN` commands? http://vimcasts.org/episodes/operating-on-search-matches-using-gn/

It seems to me they provide the same functionality. Did you write this plugin before `gn` and `gN` were introduced in Vim?

Thanks!

PS: I'm using a bunch of your other text object including: entire, function, indent, and line. They are all super useful.

**Comment by kana** [comment]
Yes I did. [`gn` was introduced in 2012](https://github.com/vim/vim/releases/tag/v7.3.610) while [vim-textobj-lastpat was written in 2008](https://github.com/kana/vim-textobj-lastpat/commit/ec4cb92486628228d1c7acce94da3d449e4bf8aa). No need to use this plugin now.
